---
apiVersion: v1
kind: Namespace
metadata:
  name: spangen
  labels: {
    istio-injection: enabled
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: spangen
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          imagePullPolicy: Never
          image: helloworld:latest
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
            - containerPort: 9090
              protocol: TCP
              name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: spangen
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obfuscator
  namespace: spangen
  labels:
    app: obfuscator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obfuscator
  template:
    metadata:
      labels:
        app: obfuscator
    spec:
      containers:
        - name: obfuscator
          imagePullPolicy: Never
          image: obfuscator:latest
          ports:
            - containerPort: 2019
              protocol: TCP
              name: grpc
            - containerPort: 9090
              protocol: TCP
              name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: obfuscator
  namespace: spangen
spec:
  selector:
    app: obfuscator
  ports:
    - protocol: TCP
      port: 2019
      targetPort: 2019
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmarker
  namespace: spangen
  labels:
    app: benchmarker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmarker
  template:
    metadata:
      labels:
        app: benchmarker
    spec:
      containers:
        - name: benchmarker
          imagePullPolicy: Never
          image: benchmarker:latest
